### ISSUE TITLE
error 0xc000007b

### ISSUE THREAD

**Issue by jonasss312** [dechamps/WinIPBroadcast#2]
To start with, it was missing dlls:
api-ms-win-core-synch-l1-2-0.dll,
api-ms-win-core-rtlsupport-l1-2-0.dll,
api-ms-win-core-memory-l1-1-2.dll.
I downloaded them.
After that, i got error (0xc000007b): The application was unable to start correctly.
Any fix for it ?
Windows 7

**Comment by dechamps** [comment]
Mmm. I might have missed something when upgrading the project to VS2017. Does version 1.3 work?

**Comment by jonasss312** [comment]
havent's used it, don't know.

**Comment by dechamps** [comment]
You can use version 1.3 (you can find it on the releases pages) until I get some time to figure out a fix. 1.5 only brings minor improvements that make no difference for most people.

**Comment by jonasss312** [comment]
maybe i started it with wrong exe?
mayeb i should go to src folder and start from there ?

**Comment by dechamps** [comment]
You should use the installer. When are you getting the error? Does it appear when you manually try to start the service? Or are you using the command line?

**Comment by jonasss312** [comment]
when i try to start it manually

**Comment by jonasss312** [comment]
maybe i installed the VS incorrectly ?

**Comment by jonasss312** [comment]
1.3 doesn't show any errors but console just pop up for miliseconds and disappears

**Comment by dechamps** [comment]
In normal operation, WinIPBroadcast runs as a service, which is started automatically by the installer. If it's running properly you should see it as a running service in your Windows service list. If that's the case then there's nothing else to do. There is no need to run the executable manually unless you're troubleshooting problems, and even then, it needs to be run from a command line if you want to see the output before it goes away.

**Comment by jonasss312** [comment]
Well it is in services, but on 1.3.
1.4 and 1.5 don't work.
Thanks anyway

**Comment by dechamps** [comment]
This should be fixed through 4dfab9ca94b9a871882c8cf789ca626b370b76f8, released in WinIPBroadcast 1.6.
