### ISSUE TITLE
CreateProcess failed; code 193, %I is not valid Win32 application

### ISSUE THREAD

**Issue by rknetwork** [dechamps/WinIPBroadcast#4]
Having troubles installing it under Windows XP SP3.

![image](https://user-images.githubusercontent.com/1091494/30335354-1b83ee64-97b0-11e7-8411-38368921e9f8.png)

**Comment by dechamps** [comment]
WinIPBroadcast does not support Windows XP, and never will. (I guess I should clarify that in the README.)

By using a decade-old OS with no security update support from Microsoft you are putting yourself and others at risk. The proper solution to your problem is to upgrade to Windows 7 or later.

**Comment by dmiranda12** [comment]
I solved it using pathPE, so it is probably a line of code. After patch it seems to work. How do I know? I filter UPD in a number of ports, and ban a zillion IPs altogether. I also log errors.  among them where a bunch of 0.0.0.0 to 255.255 etc.  They have been gone now for a couple of hours. Will confirm later on. 

https://nikkhokkho.sourceforge.io/static.php?page=PatchPE.
