### ISSUE TITLE
Just wanna say thanks !

### ISSUE THREAD

**Issue by Tangeek42** [dechamps/WinIPBroadcast#5]
Yeah yeah, I know Issues is not the place to post that, but I'm not used to Github and I may have missed the casual comments section ?

I reaaaally wanted to say thanks for this wrapper, it saved me from a good two hours of headache trying to set up a clean VPN only for games, aka without having to forward all trafic through it. I wanted just the LAN please. And you guessed it, the broadcast was making me crazy. I know you can just enter an IP and boom, it works (and it did work of course), but I really wanted to show this to some friends and go "yeah, see ? It works as good as in a LAN". Especially when some games do not have a way to enter a direct IP (Torchlight II, I'm looking at ya).

Now, if there's a few games that do not detect parties automatically because of the "same port issue", well, not that big a deal, we'll still be able to enter the IP. At the very least the risk percentage of having a game that do not work has significantly dropped. :) 

During my final tests, UT2004 detected my LAN-server twice : once for the real LAN IP, and the other for the VPN IP. Which was my fucking dream come true. Thank you !

**Comment by Tangeek42** [comment]
I'm closing the issue because, you know, it's not one, of course.

**Comment by dechamps** [comment]
You're welcome :)
